services:
  - type: web
    name: flynn-james-portfolio
    env: static
    buildCommand: null
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /services-prospecting
        destination: /services-prospecting.html
      - type: rewrite
        source: /services-appointment-setting
        destination: /services-appointment-setting.html
      - type: rewrite
        source: /services-coaching
        destination: /services-coaching.html
      - type: rewrite
        source: /how-i-work
        destination: /how-i-work.html
      - type: rewrite
        source: /experience
        destination: /experience.html
      - type: rewrite
        source: /contact
        destination: /contact.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000